name: 'Steelkiss '
favicon: null
layout_spectrum: 0.08729
typography_spectrum: 0.3389
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Grid Test
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#003585'
    - '#135aa8'
    - '#d9d2da'
    - '#497cbb'
    - '#8a8fa3'
  brandStrength: 0.125
  lightness: 0.8452808
  saturation: 0.8130227
  rhythmicContrast: 0.25
purpose: []
