name: 'Steelkiss '
favicon: null
layout_spectrum: 0.95511
typography_spectrum: 0.07417
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010101'
    - '#cacacc'
    - '#9a9b9d'
    - '#454545'
  brandStrength: 0.5
  lightness: 0.5597371
  saturation: 0.75
  rhythmicContrast: 0.379331
purpose: []
